name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - citest*
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # must be specified without patch version
          version: v1.31

          # Only show new issues for a pull request.
          only-new-issues: true
